import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {JetBrains_Mono} from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { TooltipProvider } from "@radix-ui/react-tooltip";

const myFont = localFont({
  src: [
    {
      path: "/fonts/Instagram Sans.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Instagram Sans Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "/fonts/Instagram Sans Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} bg-black selection:bg-[#D4D4C8] selection:text-black text-[#EBEBEB] max-w-xl mx-auto `}
      >
        <TooltipProvider>{children}</TooltipProvider>
        <Analytics />
      </body>
    </html>
  );
}
